# Generated by Django 5.2.1 on 2025-05-18 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MATCH', 'Nouveau match'), ('MESSAGE', 'Nouveau message'), ('LIKE', 'Nouveau like'), ('EVENT', 'Événement'), ('SUBSCRIPTION', 'Abonnement'), ('SYSTEM', 'Système')], max_length=15, verbose_name='Type')),
                ('context_type', models.CharField(choices=[('USER', 'Utilisateur'), ('EVENT', 'Événement'), ('MESSAGE', 'Message'), ('SUBSCRIPTION', 'Abonnement'), ('SYSTEM', 'Système')], max_length=15, verbose_name='Type de contexte')),
                ('context_id', models.PositiveIntegerField(verbose_name='ID de contexte')),
                ('actor_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'acteur")),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image")),
                ('action_url', models.CharField(blank=True, max_length=255, null=True, verbose_name="URL d'action")),
                ('action_text', models.CharField(blank=True, max_length=50, null=True, verbose_name="Texte de l'action")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('is_push_sent', models.BooleanField(default=False, verbose_name='Notification push envoyée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_email', models.BooleanField(default=True, verbose_name='Recevoir des emails')),
                ('receive_push', models.BooleanField(default=True, verbose_name='Recevoir des notifications push')),
                ('matches', models.BooleanField(default=True, verbose_name='Nouveaux matchs')),
                ('messages', models.BooleanField(default=True, verbose_name='Nouveaux messages')),
                ('likes', models.BooleanField(default=True, verbose_name='Nouveaux likes')),
                ('events', models.BooleanField(default=True, verbose_name='Événements')),
                ('subscription', models.BooleanField(default=True, verbose_name='Abonnement')),
                ('system', models.BooleanField(default=True, verbose_name='Système')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name="Token de l'appareil")),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=10, verbose_name='Plateforme')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'appareil")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Dernière utilisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Token d'appareil",
                'verbose_name_plural': "Tokens d'appareils",
                'unique_together': {('user', 'token')},
            },
        ),
    ]
